version: '3.1'

services:

  mongo:
    image: my-mongo
    restart: always
    container_name: 'moj-mongo'
    volumes:
      - /data/db:/data/db
      - /data/db/log:/log
    ports:
      - '27017:27017'
